// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AlMarsadDbContext))]
    [Migration("20260508173712_add AI classifying modification on database")]
    partial class addAIclassifyingmodificationondatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer")
                        .HasColumnName("account_status");

                    b.Property<bool?>("AvailabilityStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("availability_status");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiration_time");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("third_name");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_asp_net_users_city_id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_phone_number");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.AppUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_name");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("ArabicName")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_arabic_name");

                    b.HasIndex("EnglishName")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_english_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_evidences");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_evidences_incident_id");

                    b.ToTable("evidences", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.FinalIncidentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<bool>("DocumentationConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("documentation_consent");

                    b.Property<string>("FieldResearcherId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_researcher_id");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<bool>("PublicationConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("publication_consent");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_final_incident_reports");

                    b.HasIndex("FieldResearcherId")
                        .HasDatabaseName("ix_final_incident_reports_field_researcher_id");

                    b.HasIndex("IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_final_incident_reports_incident_id");

                    b.ToTable("final_incident_reports", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaClass")
                        .HasColumnType("integer")
                        .HasColumnName("area_class");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<int?>("AreaType")
                        .HasColumnType("integer")
                        .HasColumnName("area_type");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("DateOfOccurrence")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_occurrence");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detailed_description");

                    b.Property<string>("FieldResearcherId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_researcher_id");

                    b.Property<int?>("InitialIncidentReportId")
                        .HasColumnType("integer")
                        .HasColumnName("initial_incident_report_id");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("text")
                        .HasColumnName("location_description");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lat");

                    b.Property<double>("LocationLng")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lng");

                    b.Property<string>("PerpetratorDescription")
                        .HasColumnType("text")
                        .HasColumnName("perpetrator_description");

                    b.Property<string>("QuestionnaireJSON")
                        .HasColumnType("jsonb")
                        .HasColumnName("questionnaire_json");

                    b.Property<byte>("SensitivityScore")
                        .HasColumnType("smallint")
                        .HasColumnName("sensitivity_score");

                    b.Property<int?>("WitnessCount")
                        .HasColumnType("integer")
                        .HasColumnName("witness_count");

                    b.Property<string>("WitnessDetails")
                        .HasColumnType("text")
                        .HasColumnName("witness_details");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_incidents_city_id");

                    b.HasIndex("FieldResearcherId")
                        .HasDatabaseName("ix_incidents_field_researcher_id");

                    b.HasIndex("InitialIncidentReportId")
                        .HasDatabaseName("ix_incidents_initial_incident_report_id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.IncidentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IncidentClassTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_class_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incident_classes");

                    b.HasIndex("IncidentClassTypeId")
                        .HasDatabaseName("ix_incident_classes_incident_class_type_id");

                    b.ToTable("incident_classes", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.IncidentClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incident_class_types");

                    b.ToTable("incident_class_types", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.InitialIncidentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CitizenReporterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizen_reporter_id");

                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("FieldResearcherId")
                        .HasColumnType("text")
                        .HasColumnName("field_researcher_id");

                    b.Property<string>("InitialDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_description");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lat");

                    b.Property<double>("LocationLng")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lng");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WitnessName")
                        .HasColumnType("text")
                        .HasColumnName("witness_name");

                    b.Property<string>("WitnessPhone")
                        .HasColumnType("text")
                        .HasColumnName("witness_phone");

                    b.HasKey("Id")
                        .HasName("pk_initial_incident_reports");

                    b.HasIndex("CitizenReporterId")
                        .HasDatabaseName("ix_initial_incident_reports_citizen_reporter_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_initial_incident_reports_city_id");

                    b.HasIndex("FieldResearcherId")
                        .HasDatabaseName("ix_initial_incident_reports_field_researcher_id");

                    b.ToTable("initial_incident_reports", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.LegalReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinalIncidentReportId")
                        .HasColumnType("integer")
                        .HasColumnName("final_incident_report_id");

                    b.Property<string>("LegalTeamMemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_team_member_id");

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_content");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_date");

                    b.HasKey("Id")
                        .HasName("pk_legal_reviews");

                    b.HasIndex("FinalIncidentReportId")
                        .IsUnique()
                        .HasDatabaseName("ix_legal_reviews_final_incident_report_id");

                    b.HasIndex("LegalTeamMemberId")
                        .HasDatabaseName("ix_legal_reviews_legal_team_member_id");

                    b.ToTable("legal_reviews", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("WrittenById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("written_by_id");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_incident_id");

                    b.HasIndex("WrittenById")
                        .HasDatabaseName("ix_news_written_by_id");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.PersonalVictimTestimonie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<string>("InjuryDescription")
                        .HasColumnType("text")
                        .HasColumnName("injury_description");

                    b.Property<int?>("InjuryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("injury_status");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("PersonalNarrative")
                        .HasColumnType("text")
                        .HasColumnName("personal_narrative");

                    b.Property<int>("VictimId")
                        .HasColumnType("integer")
                        .HasColumnName("victim_id");

                    b.HasKey("Id")
                        .HasName("pk_personal_victim_testimonies");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_personal_victim_testimonies_incident_id");

                    b.HasIndex("VictimId")
                        .HasDatabaseName("ix_personal_victim_testimonies_victim_id");

                    b.ToTable("personal_victim_testimonies", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_body");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Victim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("FmailySize")
                        .HasColumnType("integer")
                        .HasColumnName("fmaily_size");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("marital_status");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("third_name");

                    b.HasKey("Id")
                        .HasName("pk_victims");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ix_victims_national_id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_victims_phone_number");

                    b.ToTable("victims", (string)null);
                });

            modelBuilder.Entity("IncidentClassTypeQuestion", b =>
                {
                    b.Property<int>("IncidentClassTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_class_types_id");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer")
                        .HasColumnName("questions_id");

                    b.HasKey("IncidentClassTypesId", "QuestionsId")
                        .HasName("pk_incident_class_type_question");

                    b.HasIndex("QuestionsId")
                        .HasDatabaseName("ix_incident_class_type_question_questions_id");

                    b.ToTable("incident_class_type_question", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.AppUser", b =>
                {
                    b.HasOne("DAL.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_users_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("DAL.Entities.AppUserRole", b =>
                {
                    b.HasOne("DAL.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DAL.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Evidence", b =>
                {
                    b.HasOne("DAL.Entities.Incident", "Incident")
                        .WithMany("Evidences")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_evidences_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("DAL.Entities.FinalIncidentReport", b =>
                {
                    b.HasOne("DAL.Entities.AppUser", "FieldResearcher")
                        .WithMany("FinalIncidentReports")
                        .HasForeignKey("FieldResearcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_final_incident_reports_app_user_field_researcher_id");

                    b.HasOne("DAL.Entities.Incident", "Incident")
                        .WithOne("FinalIncidentReport")
                        .HasForeignKey("DAL.Entities.FinalIncidentReport", "IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_final_incident_reports_incidents_incident_id");

                    b.Navigation("FieldResearcher");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("DAL.Entities.Incident", b =>
                {
                    b.HasOne("DAL.Entities.City", "City")
                        .WithMany("Incidents")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_cities_city_id");

                    b.HasOne("DAL.Entities.AppUser", "FieldResearcher")
                        .WithMany("Incidents")
                        .HasForeignKey("FieldResearcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_app_user_field_researcher_id");

                    b.HasOne("DAL.Entities.InitialIncidentReport", "InitialIncidentReport")
                        .WithMany("Incidents")
                        .HasForeignKey("InitialIncidentReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incidents_initial_incident_reports_initial_incident_report_");

                    b.Navigation("City");

                    b.Navigation("FieldResearcher");

                    b.Navigation("InitialIncidentReport");
                });

            modelBuilder.Entity("DAL.Entities.IncidentClass", b =>
                {
                    b.HasOne("DAL.Entities.IncidentClassType", "IncidentClassType")
                        .WithMany()
                        .HasForeignKey("IncidentClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_classes_incident_class_types_incident_class_type_id");

                    b.Navigation("IncidentClassType");
                });

            modelBuilder.Entity("DAL.Entities.InitialIncidentReport", b =>
                {
                    b.HasOne("DAL.Entities.AppUser", "CitizenReporter")
                        .WithMany("InitialIncidentReports")
                        .HasForeignKey("CitizenReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_initial_incident_reports_asp_net_users_citizen_reporter_id");

                    b.HasOne("DAL.Entities.City", "City")
                        .WithMany("InitialIncidentReports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_initial_incident_reports_cities_city_id");

                    b.HasOne("DAL.Entities.AppUser", "FieldResearcher")
                        .WithMany("AssignedInitialReports")
                        .HasForeignKey("FieldResearcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_initial_incident_reports_asp_net_users_field_researcher_id");

                    b.Navigation("CitizenReporter");

                    b.Navigation("City");

                    b.Navigation("FieldResearcher");
                });

            modelBuilder.Entity("DAL.Entities.LegalReview", b =>
                {
                    b.HasOne("DAL.Entities.FinalIncidentReport", "FinalIncidentReport")
                        .WithOne("LegalReview")
                        .HasForeignKey("DAL.Entities.LegalReview", "FinalIncidentReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_reviews_final_incident_reports_final_incident_report_");

                    b.HasOne("DAL.Entities.AppUser", "LegalTeamMember")
                        .WithMany("LegalReviews")
                        .HasForeignKey("LegalTeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_reviews_app_user_legal_team_member_id");

                    b.Navigation("FinalIncidentReport");

                    b.Navigation("LegalTeamMember");
                });

            modelBuilder.Entity("DAL.Entities.NewsItem", b =>
                {
                    b.HasOne("DAL.Entities.Incident", "Incident")
                        .WithOne("NewsItem")
                        .HasForeignKey("DAL.Entities.NewsItem", "IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_news_incidents_incident_id");

                    b.HasOne("DAL.Entities.AppUser", "WrittenBy")
                        .WithMany("News")
                        .HasForeignKey("WrittenById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_news_app_user_written_by_id");

                    b.Navigation("Incident");

                    b.Navigation("WrittenBy");
                });

            modelBuilder.Entity("DAL.Entities.PersonalVictimTestimonie", b =>
                {
                    b.HasOne("DAL.Entities.Incident", "Incident")
                        .WithMany("PersonalVictimTestimonies")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_personal_victim_testimonies_incidents_incident_id");

                    b.HasOne("DAL.Entities.Victim", "Victim")
                        .WithMany("PersonalVictimTestimonies")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_personal_victim_testimonies_victims_victim_id");

                    b.Navigation("Incident");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("IncidentClassTypeQuestion", b =>
                {
                    b.HasOne("DAL.Entities.IncidentClassType", null)
                        .WithMany()
                        .HasForeignKey("IncidentClassTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_class_type_question_incident_class_types_incident_");

                    b.HasOne("DAL.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_class_type_question_questions_questions_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DAL.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DAL.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedInitialReports");

                    b.Navigation("FinalIncidentReports");

                    b.Navigation("Incidents");

                    b.Navigation("InitialIncidentReports");

                    b.Navigation("LegalReviews");

                    b.Navigation("News");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Entities.City", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("InitialIncidentReports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Entities.FinalIncidentReport", b =>
                {
                    b.Navigation("LegalReview");
                });

            modelBuilder.Entity("DAL.Entities.Incident", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("FinalIncidentReport");

                    b.Navigation("NewsItem");

                    b.Navigation("PersonalVictimTestimonies");
                });

            modelBuilder.Entity("DAL.Entities.InitialIncidentReport", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("DAL.Entities.Victim", b =>
                {
                    b.Navigation("PersonalVictimTestimonies");
                });
#pragma warning restore 612, 618
        }
    }
}
